name: moxietechtalks
favicon: null
layout_spectrum: 0.5823486119043082
typography_spectrum: 0.6859554038383067
title: Moxie Tech Talks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0090bf'
    - '#b2d8db'
    - '#000000'
    - '#80ffff'
    - '#15406a'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
